#ifndef EXT_H
#define EXT_H
#include <stdint.h>
#include "bvm.h"

#define EXT_ARGS 0
#define EXT_STDINOUT 1
#define EXT_FILE_SYSTEM 2
#define EXT_GUI 3

// STDIN/OUT Masks
#define MASK_ID 0XFFFFFFFF
#define MASK_OPERACAO 0XFFFFFFFF00000000
#define MASK_PRINT 0X80000000
#define MASK_STRING 0X40000000
#define MASK_DOUBLE 0X20000000
#define MASK_HEX 0X10000000
#define MASK_SINAL 0X08000000
#define MASK_CSTRING 0X04000000
#define MASK_TAMANHO_INT 0X0000000F

// GUI Operations

#define INIT_WINDOW 1
#define WINDOW_SHOULD_CLOSE 2
#define CLOSE_WINDOW 3

#define CLEAR_BACKGROUND 4
#define BEGIN_DRAWING 5
#define END_DRAWING 6

#define DRAW_PIXEL 7
#define DRAW_LINE 8
#define DRAW_TRIANGLE 9
#define DRAW_RECTANGLE 10
#define DRAW_ELLIPSE 11
#define DRAW_ELLIPSE_LINES 12

#define IS_MOUSE_BUTTON_PRESSED 13
#define GET_MOUSE_POSITION 14
#define GET_TOUCH_POSITION 15

#define CHECK_COLLISION_POINT_REC 16
#define CHECK_COLLISION_POINT_CIRCLE 17
#define CHECK_COLLISION_POINT_TRIANGLE 18

#define IS_KEY_PRESSED 19
#define GET_KEY_PRESSED 20
#define GET_CHAR_PRESSED 21

#define GUI_LABEL 22
#define GUI_CHECK_BOX 23
#define GUI_BUTTON 24
#define GUI_TEXT_BOX 25
#define GUI_DROPDOWN_BOX 26
#define GUI_PROGRESS_BAR 27

int processar_extensao(uint64_t extensao, uint64_t inicio, uint64_t tamanho, bvm *vm);

#endif /* EXT_H */
